[package]

name = "hello_world"
version = "0.1.0"
authors = ["furuhama <yuuuuusuke0210@gmail.com>"]

[dependencies]

num = "0.1"
rand = "0.4"

[profile.dev]

# opt-level can be from 0 to 3
opt-level = 0

[profile.release]

opt-level = 3

